# Site setings
name: 'Simon Richebächer'
description: 'Software Architect and Business Analyst'
meta_description: 'A blog that explores theory and practice in the IT field'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'authorimage.jpg'
  greetings: "<big>Tech in Context</big> <br />  <small>A blog that explores theory and practice in the IT field</small>"
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://simon.richebaecher.org
disqus: #'justgoodthemes'
# mailchimp_url: 'https://richebaecher.us21.list-manage.com/subscribe/post?u=2eba95e41bce6b37115e5f9b4&amp;id=76c3434085&amp;f_id=0006f8e1f0'
# mailchimp_url: #'//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
# Add your GA Tracking Id
ga_analytics: G-ZPY23EZN0Z 

# Contact form setings
email: simon@richebaecher.org
contact_page_description: "Please contact me with any request you see fit."
thankyou_page_description: "Your message has been successfully sent. I will contact you as soon as possible."

# Social links
# twitter: #'justgoodthemes'
# facebook: #'username'
github: 'simonrbtech'
# codepen: #'username'
# dribbble: #'username'
# medium: #'@username'
# instagram: #'username'
# pinterest: #'username'
linkedin: 'simon-richebaecher'
# producthunt: #'@username'
# quora: #'username'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Context Posts
    url: /context
  - text: Tutorials
    url: /tutorials
  - text: Contact Me
    url: /contact
  - text: Search
    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
