# Site setings
name: 'Simon Richebächer'
description: 'Business Analyst and Software Engineer'
meta_description: 'Interface work between software development, data analytics and business process management'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'authorimage.jpg'
  greetings: "<u>Tech in Context</u> <br /> A blog examining both theory and practice in IT"
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://simon.richebaecher.org
disqus: #'justgoodthemes'
mailchimp_url: #'//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
# Add your GA Tracking Id
ga_analytics: 

# Contact form setings
email: simon@richebaecher.org
contact_page_description: "Please contact me with any request you see fit."
thankyou_page_description: "Your message has been successfully sent. I will contact you as soon as possible."

# Social links
twitter: #'justgoodthemes'
facebook: #'username'
github: #'justgoodthemes'
codepen: #'username'
dribbble: #'username'
medium: #'@username'
instagram: #'username'
pinterest: #'username'
linkedin: #'username'
producthunt: #'@username'
quora: #'username'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Context Posts
    url: /context
  - text: Tutorials
    url: /tutorials
  - text: Contact Me
    url: /contact
  - text: Search
    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
